sonar.projectKey=SS26-SE2-Codenames_Frontend
sonar.organization=ss26-se2-codenames
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main
sonar.tests=app/src/test/java
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.coverage.exclusions=**/ui/**,**/Hilt_*.kt,**/*_Hilt*.kt,**/*_Factory*.kt,**/*_MembersInjector*.kt,**/*_GeneratedInjector*.kt,**/*_ComponentTreeDeps*.kt,**/Dagger*.kt,**/CodenamesApp.kt,**/MainActivity.kt